"""add secrets columns and avg_duration_seconds

Revision ID: 5d58f3434b0e
Revises: 9270e43096f1
Create Date: 2026-04-11 02:05:16.787187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d58f3434b0e'
down_revision: Union[str, None] = '9270e43096f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('avg_duration_seconds', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('consumers', sa.Column('secrets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('providers', sa.Column('secrets', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'secrets')
    op.drop_column('consumers', 'secrets')
    op.drop_column('agents', 'avg_duration_seconds')
    # ### end Alembic commands ###
