"""add_signing_keys_and_signature

Revision ID: 8c150403cf15
Revises: f37df764e6ae
Create Date: 2026-04-11 14:43:09.430419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c150403cf15'
down_revision: Union[str, None] = 'f37df764e6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('signature', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('signing_public_key', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('signing_private_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'signing_private_key')
    op.drop_column('providers', 'signing_public_key')
    op.drop_column('agents', 'signature')
    # ### end Alembic commands ###
