"""add context to pipelines

Revision ID: 8e29ab5cc5f3
Revises: 9d50564e7f46
Create Date: 2026-04-13 22:25:42.105438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e29ab5cc5f3'
down_revision: Union[str, None] = '9d50564e7f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipelines', 'context')
    # ### end Alembic commands ###
