"""add total_steps to pipelines

Revision ID: 9d50564e7f46
Revises: d4e5f6a7b8c9
Create Date: 2026-04-13 22:18:40.374961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d50564e7f46'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumers', sa.Column('solana_wallet', sa.String(length=64), nullable=True))
    op.add_column('pipelines', sa.Column('total_steps', sa.Integer(), server_default='0', nullable=False))
    op.add_column('providers', sa.Column('stripe_connect_id', sa.String(length=255), nullable=True))
    op.add_column('providers', sa.Column('stripe_connect_status', sa.String(length=50), nullable=True))
    op.add_column('providers', sa.Column('solana_wallet', sa.String(length=64), nullable=True))
    op.alter_column('schedules', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('schedules', 'total_runs',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('tasks', sa.Column('payment_rail', sa.String(length=20), nullable=True))
    op.add_column('tasks', sa.Column('solana_tx_signature', sa.String(length=128), nullable=True))
    op.add_column('tasks', sa.Column('solana_escrow_address', sa.String(length=64), nullable=True))
    op.alter_column('webhooks', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('webhooks', 'total_deliveries',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('webhooks', 'total_failures',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhooks', 'total_failures',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('webhooks', 'total_deliveries',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('webhooks', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('tasks', 'solana_escrow_address')
    op.drop_column('tasks', 'solana_tx_signature')
    op.drop_column('tasks', 'payment_rail')
    op.alter_column('schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedules', 'total_runs',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('schedules', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('providers', 'solana_wallet')
    op.drop_column('providers', 'stripe_connect_status')
    op.drop_column('providers', 'stripe_connect_id')
    op.drop_column('pipelines', 'total_steps')
    op.drop_column('consumers', 'solana_wallet')
    # ### end Alembic commands ###
