"""add platform_fee_cents to tasks

Revision ID: 9e14a498df67
Revises: c3be5902fcc1
Create Date: 2026-04-11 02:46:09.597141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e14a498df67'
down_revision: Union[str, None] = 'c3be5902fcc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('platform_fee_cents', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'platform_fee_cents')
    # ### end Alembic commands ###
