"""add payment fields to tasks

Revision ID: c3be5902fcc1
Revises: 5d58f3434b0e
Create Date: 2026-04-11 02:21:55.103930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3be5902fcc1'
down_revision: Union[str, None] = '5d58f3434b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('payment_intent_id', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('payment_status', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('amount_authorized_cents', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('amount_captured_cents', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'amount_captured_cents')
    op.drop_column('tasks', 'amount_authorized_cents')
    op.drop_column('tasks', 'payment_status')
    op.drop_column('tasks', 'payment_intent_id')
    # ### end Alembic commands ###
