"""add pipelines table and task pipeline columns

Revision ID: f37df764e6ae
Revises: 9e14a498df67
Create Date: 2026-04-11 12:50:06.852612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f37df764e6ae'
down_revision: Union[str, None] = '9e14a498df67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('consumer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('callback_url', sa.Text(), nullable=True),
    sa.Column('max_cost_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_authorized_cents', sa.Integer(), nullable=False),
    sa.Column('total_captured_cents', sa.Integer(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('chain_trust_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('pipeline_id', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('step_index', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'pipelines', ['pipeline_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'step_index')
    op.drop_column('tasks', 'pipeline_id')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
